# Generated by Django 2.1.7 on 2019-03-04 23:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20190304_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('total', models.PositiveIntegerField()),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(10, 'Cash'), (20, 'Credit Card'), (30, 'Tpaga Wallet')], default=30)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='TpagaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_token', models.UUIDField(default=uuid.uuid4)),
                ('tpaga_token', models.CharField(blank=True, max_length=100)),
                ('user_ip_address', models.GenericIPAddressField()),
                ('expires_at', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'Created'), (20, 'Paid'), (30, 'Failed'), (40, 'Expired'), (50, 'Delivered'), (60, 'Reverted')], default=10)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('sale', 'product', 'inventory')},
        ),
    ]
