# Generated by Django 2.1.7 on 2019-03-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190304_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
