# Generated by Django 2.1.7 on 2019-03-05 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190304_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='subtotal',
        ),
    ]
