# Generated by Django 2.1.7 on 2019-03-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='current_amount',
            new_name='current_quantity',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='input_amount',
            new_name='input_quantity',
        ),
    ]
