# Generated by Django 2.1.7 on 2019-03-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190304_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_per_unity',
            new_name='price_per_unit',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unity',
            new_name='unit',
        ),
    ]
